/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kito Mahique
 */
public class Listar extends javax.swing.JFrame {

    /**
     * Creates new form Registar
     */
     ProcessoPadrao processo= new ProcessoPadrao("listagem");
     MedicoPadrao medico = new MedicoPadrao("listagem");
     AntecedentesCriminaisPadrao crime= new AntecedentesCriminaisPadrao("listagem");
     
    public Listar() {
        setVisible(true);
        initComponents();
        jpTela.add(processo);
        jpTela.add(medico);
        jpTela.add(crime);
        processo.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jpMenu = new javax.swing.JPanel();
        jbProcesso = new javax.swing.JButton();
        jbMedico = new javax.swing.JButton();
        jbCrimes = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jpTela = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("jButton1");

        jpMenu.setBackground(new java.awt.Color(137, 137, 98));
        jpMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpMenu.setForeground(java.awt.Color.gray);

        jbProcesso.setBackground(new java.awt.Color(0, 102, 102));
        jbProcesso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbProcesso.setForeground(new java.awt.Color(255, 255, 255));
        jbProcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2410009_jail_law_prison_crime_justice_icon.png"))); // NOI18N
        jbProcesso.setText("Processo");
        jbProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProcessoActionPerformed(evt);
            }
        });

        jbMedico.setBackground(new java.awt.Color(0, 102, 102));
        jbMedico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbMedico.setForeground(new java.awt.Color(255, 255, 255));
        jbMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/8726080_medical_square_icon.png"))); // NOI18N
        jbMedico.setText("Informacao Medica");
        jbMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMedicoActionPerformed(evt);
            }
        });

        jbCrimes.setBackground(new java.awt.Color(0, 102, 102));
        jbCrimes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCrimes.setForeground(new java.awt.Color(255, 255, 255));
        jbCrimes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5243654_crime_handcuff_manacles_shackles_speedcuffs_icon.png"))); // NOI18N
        jbCrimes.setText("Antecedentes Criminais");
        jbCrimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrimesActionPerformed(evt);
            }
        });

        jbCancelar.setBackground(new java.awt.Color(0, 102, 102));
        jbCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cancel.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCrimes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbCrimes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpTela.setBackground(java.awt.Color.darkGray);
        jpTela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));

        javax.swing.GroupLayout jpTelaLayout = new javax.swing.GroupLayout(jpTela);
        jpTela.setLayout(jpTelaLayout);
        jpTelaLayout.setHorizontalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpTelaLayout.setVerticalGroup(
            jpTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpTela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProcessoActionPerformed
        // TODO add your handling code here:
        medico.setVisible(false);
        crime.setVisible(false);
        processo.setVisible(true);
    }//GEN-LAST:event_jbProcessoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
          int a= JOptionPane.showConfirmDialog(null, "DESEJA CANCELAR?", "CANCELAR", JOptionPane.YES_NO_OPTION);
          if(a==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Chamar a tela anterior");
          }
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMedicoActionPerformed
        processo.setVisible(false);
        crime.setVisible(false);
        medico.setVisible(true);
    }//GEN-LAST:event_jbMedicoActionPerformed

    private void jbCrimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrimesActionPerformed
        medico.setVisible(false);
        processo.setVisible(false);
        crime.setVisible(true);
    }//GEN-LAST:event_jbCrimesActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registar().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCrimes;
    private javax.swing.JButton jbMedico;
    private javax.swing.JButton jbProcesso;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpTela;
    // End of variables declaration//GEN-END:variables
}
