/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ButtonGroup;

/**
 *
 * @author Kito Mahique
 * lembrar que esta tela faze parte das telas nao usadas no sistema.
 * Telas nao usadas neste sistema:
 * - ProcessoPadrao
 * - MedicoPadrao
 * - AntecedentesCriminaisPadrao
 */
public class MedicoPadrao extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistoMedico
     */
    Font f1= new Font("Calibre", Font.BOLD,18);
    public MedicoPadrao(String finalidade) {
        initComponents();
        if(finalidade.equals("listagem")){
            jtDoenca.setBackground(Color.darkGray);
            jtaCuidados.setBackground(Color.darkGray);
            
            jtDoenca.setForeground(Color.cyan);
            jtaCuidados.setForeground(Color.cyan);
            
            jtDoenca.setFont(f1);
            jtaCuidados.setFont(f1);
        }
        
        jbConcluirMedico.setEnabled(false);
        getContentPane().setBackground(Color.DARK_GRAY);
        jbConcluirMedico.setBackground(Color.white);
        jbVoltar.setBackground(Color.white);
        jbEditar.setBackground(Color.white);
        
        jtId.setEnabled(false);
        jtaCuidados.setEnabled(false);
        jtDoenca.setEnabled(false);
         ButtonGroup bgDoenca= new ButtonGroup();
         bgDoenca.add(jrDoencaSim);
         bgDoenca.add(jrDoencaNao);
    }
    private void habilitarBotaoConcluir(){
         if((jtDoenca.getText().length()>3) && (jtaCuidados.getText().length()>3)){
            jbConcluirMedico.setEnabled(true);
        }else{
            jbConcluirMedico.setEnabled(false);
        }
    }
    public void desabilitarCampos(){
        jrDoencaSim.setEnabled(false);
        jrDoencaNao.setEnabled(false);
        jtDoenca.setEnabled(false);
        jtaCuidados.setEnabled(false);
    }
    public void habilitarCampos(){
        jrDoencaSim.setEnabled(true);
        jrDoencaNao.setEnabled(true);
        jtDoenca.setEnabled(true);
        jtaCuidados.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlId = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jlimag = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlSofre = new javax.swing.JLabel();
        jlnomed = new javax.swing.JLabel();
        jlcudados = new javax.swing.JLabel();
        jrDoencaSim = new javax.swing.JRadioButton();
        jrDoencaNao = new javax.swing.JRadioButton();
        jtDoenca = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbConcluirMedico = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCuidados = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Informacao Medica");
        setPreferredSize(new java.awt.Dimension(1205, 590));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlId.setText("ID");

        jlimag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prisoner.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/8726080_medical_square_icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlimag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jlimag))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jlSofre.setBackground(new java.awt.Color(255, 255, 255));
        jlSofre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlSofre.setForeground(new java.awt.Color(255, 255, 255));
        jlSofre.setText("Alguma doenca/deficiencia");

        jlnomed.setBackground(new java.awt.Color(255, 255, 255));
        jlnomed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlnomed.setForeground(new java.awt.Color(255, 255, 255));
        jlnomed.setText("Nome da doenca");

        jlcudados.setBackground(new java.awt.Color(255, 255, 255));
        jlcudados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlcudados.setForeground(new java.awt.Color(255, 255, 255));
        jlcudados.setText("Cuidados Basicos");

        jrDoencaSim.setBackground(new java.awt.Color(255, 255, 255));
        jrDoencaSim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jrDoencaSim.setText("Sim");
        jrDoencaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDoencaSimActionPerformed(evt);
            }
        });

        jrDoencaNao.setBackground(new java.awt.Color(255, 255, 255));
        jrDoencaNao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jrDoencaNao.setText("Nao");
        jrDoencaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDoencaNaoActionPerformed(evt);
            }
        });

        jtDoenca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtDoenca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jtDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDoencaActionPerformed(evt);
            }
        });
        jtDoenca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtDoencaKeyReleased(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(java.awt.Color.pink);

        jbConcluirMedico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbConcluirMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1891021_approved_check_checkbox_checkmark_confirm_icon.png"))); // NOI18N
        jbConcluirMedico.setText("  Concluir");
        jbConcluirMedico.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jbConcluirMedico.setName("Processo"); // NOI18N
        jbConcluirMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConcluirMedicoActionPerformed(evt);
            }
        });
        jbConcluirMedico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbConcluirMedicoKeyReleased(evt);
            }
        });

        jbEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/314251_edit_document_icon_1.png"))); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2303135_arrow_back_left_refresh_renew_icon.png"))); // NOI18N
        jbVoltar.setText("Voltar");
        jbVoltar.setName("Processo"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jbConcluirMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConcluirMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jtaCuidados.setColumns(20);
        jtaCuidados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtaCuidados.setRows(5);
        jtaCuidados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtaCuidadosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtaCuidados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlnomed, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSofre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlcudados, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtDoenca, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrDoencaSim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrDoencaNao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(221, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlSofre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jrDoencaSim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jrDoencaNao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlnomed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlcudados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 1205, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void jrDoencaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDoencaSimActionPerformed
                // TODO add your handling code here:
                 jtaCuidados.setEnabled(true);
                 jtDoenca.setEnabled(true);
                 if(jtDoenca.getText().length()<4 || jtaCuidados.getText().length()<4){
                     jbConcluirMedico.setEnabled(false);
                 }
    }//GEN-LAST:event_jrDoencaSimActionPerformed

    private void jrDoencaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDoencaNaoActionPerformed
        // TODO add your handling code here:
        jtaCuidados.setText("");
        jtDoenca.setText("");
        jtaCuidados.setEnabled(false);
        jtDoenca.setEnabled(false);
        jbConcluirMedico.setEnabled(true);
    }//GEN-LAST:event_jrDoencaNaoActionPerformed

    private void jbConcluirMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConcluirMedicoActionPerformed
        // TODO add your handling code here:
        desabilitarCampos();
    }//GEN-LAST:event_jbConcluirMedicoActionPerformed

    private void jtDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDoencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDoencaActionPerformed

    private void jbConcluirMedicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbConcluirMedicoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jbConcluirMedicoKeyReleased

    private void jtaCuidadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaCuidadosKeyReleased
        // TODO add your handling code here:
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jtaCuidadosKeyReleased

    private void jtDoencaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDoencaKeyReleased
        // TODO add your handling code here:
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jtDoencaKeyReleased

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
         if(jrDoencaSim.isSelected()){
             habilitarCampos();
         }
    }//GEN-LAST:event_jbEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbConcluirMedico;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlSofre;
    private javax.swing.JLabel jlcudados;
    private javax.swing.JLabel jlimag;
    private javax.swing.JLabel jlnomed;
    private javax.swing.JRadioButton jrDoencaNao;
    private javax.swing.JRadioButton jrDoencaSim;
    private javax.swing.JTextField jtDoenca;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextArea jtaCuidados;
    // End of variables declaration//GEN-END:variables
}
