package view;

import controller.ProcessoController;
import java.awt.Color;
import javax.swing.ButtonGroup;

/**
 *
 * @author Kito Mahique
 */
public class RegistarProcesso extends javax.swing.JFrame {

    /**
     * Creates new form RegistarProcesso
     */
    ButtonGroup bgGenero= new ButtonGroup();
    ButtonGroup bgCrime= new ButtonGroup();
    ButtonGroup bgDoenca= new ButtonGroup();
    
    public RegistarProcesso() {
        initComponents();
        data();
        jtId.setEnabled(false);
        jbRegistar.setEnabled(false);
        getContentPane().setBackground(Color.DARK_GRAY);
        setLocationRelativeTo(null);
        
        bgGenero.add(jrMasculino);
        bgGenero.add(jrFeminino);
        
        bgCrime.add(jrCrimeSim);
        bgCrime.add(jrCrimeNao);
        
        bgDoenca.add(jrDoencaSim);
        bgDoenca.add(jrDoencaNao);
        jbVoltar.setBackground(Color.white);
        jbRegistar.setBackground(Color.white);
    }
    public void data(){
        for(int i=1; i<=31; i++){
           String a=String.valueOf(i);
           jcDia.addItem(a);
       }
       jcMes.addItem("Janeiro"); jcMes.addItem("Fevereiro"); jcMes.addItem("Março"); 
        jcMes.addItem("Abril"); jcMes.addItem("Maio"); jcMes.addItem("junho"); 
        jcMes.addItem("Julho"); jcMes.addItem("Agosto"); jcMes.addItem("Setembro"); 
        jcMes.addItem("Outubro"); jcMes.addItem("Novembro"); jcMes.addItem("Dezembro"); 
       for(int i=2023; i>=1970; i--){
           String a=String.valueOf(i);
           jcAno.addItem(a);
       }
    }
    
    private void habilitarBotaoConcluir(){
        if(jtNome.getText().length()>2 && jtBi.getText().length()>2 && 
                jtNacionalidade.getText().length()>2 && jtNaturalidade.getText().length()>2 &&
                jtLocalDeResidencia.getText().length()>2 && (jrMasculino.isSelected() || 
                jrFeminino.isSelected()) && jrDoencaSim.isSelected() && jtDoenca.getText().length()>2
                && jtaCuidados.getText().length()>2 && jrCrimeSim.isSelected() && jtaCrimes.getText().length()>2){
                jbRegistar.setEnabled(true);
        } 
        if(jtNome.getText().length()>2 && jtBi.getText().length()>2 && 
                jtNacionalidade.getText().length()>2 && jtNaturalidade.getText().length()>2 &&
                jtLocalDeResidencia.getText().length()>2 && (jrMasculino.isSelected() || 
                jrFeminino.isSelected()) && jrDoencaNao.isSelected() &&
                jrCrimeNao.isSelected()){
                jbRegistar.setEnabled(true);
        }
        if(jtNome.getText().length()<3 || jtBi.getText().length()<3 || 
                jtNacionalidade.getText().length()<3 || jtNaturalidade.getText().length()<3 ||
                jtLocalDeResidencia.getText().length()<3){
                jbRegistar.setEnabled(false);
        }
        
        if((jrCrimeSim.isSelected() && jtaCrimes.getText().length()<3) || 
                (jrDoencaSim.isSelected() && jtDoenca.getText().length()<3 && 
                jtaCuidados.getText().length()<3)){
            jbRegistar.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlId = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jlimag = new javax.swing.JLabel();
        jpProcesso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlNacionalidade = new javax.swing.JLabel();
        jtNacionalidade = new javax.swing.JTextField();
        jlBi = new javax.swing.JLabel();
        jlNaturalidade = new javax.swing.JLabel();
        jtBi = new javax.swing.JTextField();
        jtNaturalidade = new javax.swing.JTextField();
        jlData = new javax.swing.JLabel();
        jcAno = new javax.swing.JComboBox<>();
        jcMes = new javax.swing.JComboBox<>();
        jcDia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jtLocalDeResidencia = new javax.swing.JTextField();
        jpGenero = new javax.swing.JPanel();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jlSofre = new javax.swing.JLabel();
        jlnomed = new javax.swing.JLabel();
        jtDoenca = new javax.swing.JTextField();
        jlcudados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaCuidados = new javax.swing.JTextArea();
        jrDoencaNao = new javax.swing.JRadioButton();
        jrDoencaSim = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jrCrimeSim = new javax.swing.JRadioButton();
        jrCrimeNao = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaCrimes = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jbRegistar = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlId.setText("ID");

        jlimag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prisoner.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlimag))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jlId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jlimag)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jpProcesso.setBackground(java.awt.Color.darkGray);
        jpProcesso.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Processo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome Completo");

        jtNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtNomeKeyReleased(evt);
            }
        });

        jlNacionalidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlNacionalidade.setForeground(new java.awt.Color(255, 255, 255));
        jlNacionalidade.setText("Nacionalidade");

        jtNacionalidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtNacionalidade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jtNacionalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtNacionalidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNacionalidadeKeyTyped(evt);
            }
        });

        jlBi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlBi.setForeground(new java.awt.Color(255, 255, 255));
        jlBi.setText("Numero de BI");

        jlNaturalidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlNaturalidade.setForeground(new java.awt.Color(255, 255, 255));
        jlNaturalidade.setText("Naturalidade");

        jtBi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtBi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jtBi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtBiKeyReleased(evt);
            }
        });

        jtNaturalidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtNaturalidade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jtNaturalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtNaturalidadeKeyReleased(evt);
            }
        });

        jlData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlData.setForeground(new java.awt.Color(255, 255, 255));
        jlData.setText("Data de Nascimento");

        jcAno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcAnoKeyReleased(evt);
            }
        });

        jcMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcMesKeyReleased(evt);
            }
        });

        jcDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcDiaKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Local de Residencia");

        jtLocalDeResidencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtLocalDeResidencia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jtLocalDeResidencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtLocalDeResidenciaKeyReleased(evt);
            }
        });

        jpGenero.setBackground(java.awt.Color.darkGray);
        jpGenero.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Genero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jrMasculino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jrMasculino.setText("Masculino");
        jrMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMasculinoActionPerformed(evt);
            }
        });
        jrMasculino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jrMasculinoKeyReleased(evt);
            }
        });

        jrFeminino.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jrFeminino.setText("Feminino");
        jrFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrFemininoActionPerformed(evt);
            }
        });
        jrFeminino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jrFemininoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jpGeneroLayout = new javax.swing.GroupLayout(jpGenero);
        jpGenero.setLayout(jpGeneroLayout);
        jpGeneroLayout.setHorizontalGroup(
            jpGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGeneroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jpGeneroLayout.setVerticalGroup(
            jpGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGeneroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jrMasculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrFeminino)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpProcessoLayout = new javax.swing.GroupLayout(jpProcesso);
        jpProcesso.setLayout(jpProcessoLayout);
        jpProcessoLayout.setHorizontalGroup(
            jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProcessoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpProcessoLayout.createSequentialGroup()
                        .addGroup(jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpProcessoLayout.createSequentialGroup()
                                .addComponent(jlData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcDia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcAno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpProcessoLayout.createSequentialGroup()
                                .addComponent(jlNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpProcessoLayout.createSequentialGroup()
                                .addComponent(jlNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpProcessoLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtLocalDeResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpProcessoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jlBi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtBi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(jpGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpProcessoLayout.setVerticalGroup(
            jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProcessoLayout.createSequentialGroup()
                .addGroup(jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProcessoLayout.createSequentialGroup()
                        .addGroup(jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlBi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtBi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jpGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcAno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtLocalDeResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpProcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcMes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jcDia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        jPanel2.setBackground(java.awt.Color.darkGray);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registo Medico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jlSofre.setBackground(new java.awt.Color(255, 255, 255));
        jlSofre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlSofre.setForeground(new java.awt.Color(255, 255, 255));
        jlSofre.setText("Alguma doenca/deficiencia");

        jlnomed.setBackground(new java.awt.Color(255, 255, 255));
        jlnomed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlnomed.setForeground(new java.awt.Color(255, 255, 255));
        jlnomed.setText("Nome da doenca");

        jtDoenca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtDoenca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jtDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDoencaActionPerformed(evt);
            }
        });
        jtDoenca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtDoencaKeyReleased(evt);
            }
        });

        jlcudados.setBackground(new java.awt.Color(255, 255, 255));
        jlcudados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlcudados.setForeground(new java.awt.Color(255, 255, 255));
        jlcudados.setText("Cuidados Basicos");

        jtaCuidados.setColumns(20);
        jtaCuidados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtaCuidados.setRows(5);
        jtaCuidados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtaCuidadosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtaCuidados);

        jrDoencaNao.setBackground(new java.awt.Color(255, 255, 255));
        jrDoencaNao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jrDoencaNao.setText("Nao");
        jrDoencaNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDoencaNaoActionPerformed(evt);
            }
        });
        jrDoencaNao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jrDoencaNaoKeyReleased(evt);
            }
        });

        jrDoencaSim.setBackground(new java.awt.Color(255, 255, 255));
        jrDoencaSim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jrDoencaSim.setText("Sim");
        jrDoencaSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrDoencaSimActionPerformed(evt);
            }
        });
        jrDoencaSim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jrDoencaSimKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSofre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlnomed, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jrDoencaSim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrDoencaNao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlcudados, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlcudados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSofre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrDoencaNao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrDoencaSim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlnomed, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel3.setBackground(java.awt.Color.darkGray);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Antecedentes Criminais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Possui Algum Registo Criminal");

        jrCrimeSim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jrCrimeSim.setText("Sim");
        jrCrimeSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCrimeSimActionPerformed(evt);
            }
        });
        jrCrimeSim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jrCrimeSimKeyReleased(evt);
            }
        });

        jrCrimeNao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jrCrimeNao.setText("Nao");
        jrCrimeNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCrimeNaoActionPerformed(evt);
            }
        });
        jrCrimeNao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jrCrimeNaoKeyReleased(evt);
            }
        });

        jLabel4.setBackground(java.awt.Color.darkGray);
        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Datas de Condenacao  -  crimes  -  sentenca");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("exemplo:   20/10/2023 - furto(subtracao) - quatro(4) anos + multa");

        jtaCrimes.setColumns(20);
        jtaCrimes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtaCrimes.setRows(5);
        jtaCrimes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtaCrimesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtaCrimes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrCrimeNao)
                            .addComponent(jrCrimeSim)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(148, 148, 148)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jrCrimeSim)
                        .addGap(18, 18, 18)
                        .addComponent(jrCrimeNao))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(java.awt.Color.gray);
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.cyan, 3));

        jbRegistar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbRegistar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/8396408_floppydisk_diskette_disk_save_file_icon.png"))); // NOI18N
        jbRegistar.setText("Registar");
        jbRegistar.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        jbRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistarActionPerformed(evt);
            }
        });

        jbVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2303135_arrow_back_left_refresh_renew_icon.png"))); // NOI18N
        jbVoltar.setText("Voltar");
        jbVoltar.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(jbRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpProcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpProcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyReleased
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jtNomeKeyReleased

    private void jtBiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBiKeyReleased
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jtBiKeyReleased

    private void jtNaturalidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNaturalidadeKeyReleased
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jtNaturalidadeKeyReleased

    private void jtNacionalidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNacionalidadeKeyReleased
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jtNacionalidadeKeyReleased

    private void jtLocalDeResidenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtLocalDeResidenciaKeyReleased
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jtLocalDeResidenciaKeyReleased

    private void jrMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMasculinoActionPerformed
        // TODO add your handling code here:
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jrMasculinoActionPerformed

    private void jrMasculinoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMasculinoKeyReleased
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jrMasculinoKeyReleased

    private void jrFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrFemininoActionPerformed
        // TODO add your handling code here:
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jrFemininoActionPerformed

    private void jrFemininoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrFemininoKeyReleased
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jrFemininoKeyReleased

    private void jtDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDoencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDoencaActionPerformed

    private void jtDoencaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDoencaKeyReleased
        habilitarBotaoConcluir();
        if(jrDoencaSim.isSelected() && (jtDoenca.getText().length()<3 || 
                jtaCuidados.getText().length()<3)){
            jbRegistar.setEnabled(false);
        }
    }//GEN-LAST:event_jtDoencaKeyReleased

    private void jtaCuidadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaCuidadosKeyReleased
       habilitarBotaoConcluir();
       if(jrDoencaSim.isSelected() && (jtDoenca.getText().length()<3 || 
                jtaCuidados.getText().length()<3)){
            jbRegistar.setEnabled(false);
        }
    }//GEN-LAST:event_jtaCuidadosKeyReleased

    private void jtNacionalidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNacionalidadeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNacionalidadeKeyTyped

    private void jtaCrimesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaCrimesKeyReleased
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jtaCrimesKeyReleased

    private void jcDiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcDiaKeyReleased
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jcDiaKeyReleased

    private void jcMesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcMesKeyReleased
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jcMesKeyReleased

    private void jcAnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcAnoKeyReleased
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jcAnoKeyReleased

    private void jrDoencaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDoencaNaoActionPerformed
        // TODO add your handling code here:
        jtDoenca.setText("");
        jtaCuidados.setText("");
        jtDoenca.setEditable(false);
        jtaCuidados.setEditable(false);
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jrDoencaNaoActionPerformed

    private void jrDoencaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrDoencaSimActionPerformed
        // TODO add your handling code here:
        jtDoenca.setEditable(true);
        jtaCuidados.setEditable(true);
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jrDoencaSimActionPerformed

    private void jrCrimeSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCrimeSimActionPerformed
        // TODO add your handling code here:
        jtaCrimes.setEditable(true);
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jrCrimeSimActionPerformed

    private void jrCrimeNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCrimeNaoActionPerformed
        // TODO add your handling code here:
        jtaCrimes.setText("");
        jtaCrimes.setEditable(false);
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jrCrimeNaoActionPerformed

    private void jrDoencaSimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrDoencaSimKeyReleased
        // TODO add your handling code here:
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jrDoencaSimKeyReleased

    private void jrDoencaNaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrDoencaNaoKeyReleased
        // TODO add your handling code here:
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jrDoencaNaoKeyReleased

    private void jrCrimeSimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCrimeSimKeyReleased
        // TODO add your handling code here:
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jrCrimeSimKeyReleased

    private void jrCrimeNaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCrimeNaoKeyReleased
        // TODO add your handling code here:
        habilitarBotaoConcluir();
    }//GEN-LAST:event_jrCrimeNaoKeyReleased

    private void jbRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistarActionPerformed
        // TODO add your handling code here:
        ProcessoController p = new ProcessoController();
        String genero;
        String doenca="";
        String crime;
        if(jrMasculino.isSelected()){
            genero ="masculino";
        }else{
            genero= "feminino";
        }
        if(jrDoencaSim.isSelected()){
            doenca = "sim";
        }else{
            doenca= "nao";
        }
        if(jrCrimeSim.isSelected()){
            crime = "sim";
        }else{
            crime = "nao";
        }
        p.gravar(jtNome.getText(), jtBi.getText(), jtNaturalidade.getText(), 
                jtNacionalidade.getText(), jtLocalDeResidencia.getText(), 
                genero, String.valueOf(jcDia.getSelectedItem())+"/"+ 
                String.valueOf(jcMes.getSelectedItem())+"/"+ 
                String.valueOf(jcAno.getSelectedItem()), doenca, jtDoenca.getText(), 
                jtaCuidados.getText(), crime, jtaCrimes.getText());
        
        new Menu();
        this.dispose();
    }//GEN-LAST:event_jbRegistarActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistarProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistarProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistarProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistarProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistarProcesso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbRegistar;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JComboBox<String> jcAno;
    private javax.swing.JComboBox<String> jcDia;
    private javax.swing.JComboBox<String> jcMes;
    private javax.swing.JLabel jlBi;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlNacionalidade;
    private javax.swing.JLabel jlNaturalidade;
    private javax.swing.JLabel jlSofre;
    private javax.swing.JLabel jlcudados;
    private javax.swing.JLabel jlimag;
    private javax.swing.JLabel jlnomed;
    private javax.swing.JPanel jpGenero;
    private javax.swing.JPanel jpProcesso;
    private javax.swing.JRadioButton jrCrimeNao;
    private javax.swing.JRadioButton jrCrimeSim;
    private javax.swing.JRadioButton jrDoencaNao;
    private javax.swing.JRadioButton jrDoencaSim;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JTextField jtBi;
    private javax.swing.JTextField jtDoenca;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtLocalDeResidencia;
    private javax.swing.JTextField jtNacionalidade;
    private javax.swing.JTextField jtNaturalidade;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextArea jtaCrimes;
    private javax.swing.JTextArea jtaCuidados;
    // End of variables declaration//GEN-END:variables
}
